update earthly test files

diff --git a/test/earthly/Earthfile b/test/earthly/Earthfile
--- a/test/earthly/Earthfile
+++ b/test/earthly/Earthfile
@@ -19,6 +19,7 @@ RUN apk add --update --no-cache \
     less \
     make \
     openssl \
+    openssh \
     util-linux
 
 WORKDIR /earthly
@@ -130,7 +131,7 @@ lint-scripts:
 earthly-script-no-stdout:
     # This validates the ./earthly script doesn't print anything to stdout (it should print to stderr)
     # This is to ensure commands such as: MYSECRET="$(./earthly secrets get -n /user/my-secret)" work
-    FROM earthly/dind:alpine-3.18-docker-23.0.6-r7
+    FROM earthly/dind:alpine-3.19-docker-25.0.5-r0
     RUN apk add --no-cache --update bash
     COPY earthly .earthly_version_flag_overrides .
 
@@ -214,10 +215,17 @@ mocks:
         SAVE ARTIFACT $mockfile AS LOCAL $mockfile
     END
 
+unit-test-parser:
+    FROM +deps
+    COPY scripts/unit-test-parser/main.go .
+    RUN go build -o testparser main.go
+    SAVE ARTIFACT testparser
+
 # unit-test runs unit tests (and some integration tests).
 unit-test:
     FROM +code
     RUN apk add --no-cache --update podman fuse-overlayfs
+    COPY +unit-test-parser/testparser .
     COPY not-a-unit-test.sh .
 
     ARG testname # when specified, only run specific unit-test, otherwise run all.
@@ -266,7 +274,8 @@ unit-test:
 # offline-test runs offline tests with network set to none
 offline-test:
     FROM +code
-    RUN --network=none go test -run TestOffline ./...
+    RUN --network=none (go test -run TestOffline ./cloud || kill $$) | tee test.log
+    RUN if grep 'no tests to run' test.log; then echo "error: no test found" && exit 1; fi
 
 # submodule-decouple-check checks that go submodules within earthly do not
 # depend on the core earthly project.
@@ -473,7 +482,7 @@ earthly-docker:
 # if no dockerhub mirror is not set it will attempt to login to dockerhub using the provided docker hub username and token.
 # Otherwise, it will attempt to login to the docker hub mirror using the provided username and password
 earthly-integration-test-base:
-    FROM +earthly-docker
+    FROM --pass-args +earthly-docker
     RUN apk update && apk add pcre-tools curl python3 bash perl findutils expect yq && apk add --upgrade sed
     COPY scripts/acbtest/acbtest scripts/acbtest/acbgrep /bin/
     ENV NO_DOCKER=1
@@ -544,39 +553,6 @@ ci-release:
     COPY (+earthly/earthly --DEFAULT_BUILDKITD_IMAGE="docker.io/earthly/buildkitd-staging:${EARTHLY_GIT_HASH}-${TAG_SUFFIX}" --VERSION=${EARTHLY_GIT_HASH}-${TAG_SUFFIX} --DEFAULT_INSTALLATION_NAME=earthly) ./earthly-linux-amd64
     SAVE IMAGE --push earthly/earthlybinaries:${EARTHLY_GIT_HASH}-${TAG_SUFFIX}
 
-# dind builds both the alpine and ubuntu dind containers for earthly
-dind:
-    # OS_IMAGE is the base image to use, e.g. alpine, ubuntu
-    ARG --required OS_IMAGE
-    # OS_VERSION is the version of the base OS to use, e.g. 3.18.0, 23.04
-    ARG --required OS_VERSION
-    # DOCKER_VERSION is the version of docker to use, e.g. 20.10.14
-    ARG --required DOCKER_VERSION
-    FROM $OS_IMAGE:$OS_VERSION
-    COPY ./buildkitd/docker-auto-install.sh /usr/local/bin/docker-auto-install.sh
-    RUN docker-auto-install.sh
-    LET DOCKER_VERSION_TAG=$DOCKER_VERSION
-    IF [ "$OS_IMAGE" = "ubuntu" ]
-        # the docker ce repo contains packages such as "5:24.0.4-1~ubuntu.20.04~focal", we will remove the the epoch and debian-revision values,
-        # in order to display the upstream-version, e.g. "24.0.5-1".
-        SET DOCKER_VERSION_TAG="$(echo $DOCKER_VERSION | sed 's/^[0-9]*:\([^~]*\).*$/\1/')"
-        RUN if echo $DOCKER_VERSION_TAG | grep "[^0-9.-]"; then echo "DOCKER_VERSION_TAG looks bad; got $DOCKER_VERSION_TAG" && exit 1; fi
-    END
-    LET TAG=$OS_IMAGE-$OS_VERSION-docker-$DOCKER_VERSION_TAG
-    ARG INCLUDE_TARGET_TAG_DOCKER=true
-    IF [ "$INCLUDE_TARGET_TAG_DOCKER" = "true" ]
-      ARG EARTHLY_TARGET_TAG_DOCKER
-      SET TAG=$TAG-$EARTHLY_TARGET_TAG_DOCKER
-    END
-    ARG DOCKERHUB_USER=earthly
-    IF [ "$LATEST" = "true" ]
-      # latest means the version is ommitted (for historical reasons we initially just called it earthly/dind:alpine or earthly/dind:ubuntu)
-      SAVE IMAGE --push --cache-from=earthly/dind:$OS_IMAGE-main $DOCKERHUB_USER/dind:$OS_IMAGE
-    END
-    ARG DATETIME="$(date --utc +%Y%m%d%H%M%S)" # note this must be overriden when building a multi-platform image (otherwise the values wont match)
-    SAVE IMAGE --push --cache-from=earthly/dind:$OS_IMAGE-main $DOCKERHUB_USER/dind:$TAG "$DOCKERHUB_USER/dind:$TAG-$DATETIME"
-
-
 # for-own builds earthly-buildkitd and the earthly CLI for the current system
 # and saves the final CLI binary locally at ./build/own/earthly
 for-own:
@@ -585,8 +561,21 @@ for-own:
     # the documentation on +earthly for extra detail about this option.
     ARG GO_GCFLAGS
     BUILD ./buildkitd+buildkitd --BUILDKIT_PROJECT="$BUILDKIT_PROJECT"
+    BUILD +build-ticktock
     COPY (+earthly/earthly --GO_GCFLAGS="${GO_GCFLAGS}") ./
     SAVE ARTIFACT ./earthly AS LOCAL ./build/own/earthly
+
+# build-ticktock is used for building the ticktock version of buildkit
+# it is only used when BUILDKIT_PROJECT is not overridden
+build-ticktock:
+    ARG BUILDKIT_PROJECT
+    IF [ -z "$BUILDKIT_PROJECT" ]
+        COPY earthly-next .
+        LET ticktock="$(cat earthly-next)"
+        ARG EARTHLY_TARGET_TAG_DOCKER
+        LET BUILDKIT_TAG="dev-$EARTHLY_TARGET_TAG_DOCKER-ticktock"
+        BUILD --platform=linux/amd64 ./buildkitd+buildkitd --BUILDKIT_PROJECT="github.com/earthly/buildkit:$ticktock" --TAG=$BUILDKIT_TAG
+    END
 
 # for-linux builds earthly-buildkitd and the earthly CLI for the a linux amd64 system
 # and saves the final CLI binary locally in the ./build/linux folder.
@@ -594,6 +583,7 @@ for-linux:
     ARG BUILDKIT_PROJECT
     ARG GO_GCFLAGS
     BUILD --platform=linux/amd64 ./buildkitd+buildkitd --BUILDKIT_PROJECT="$BUILDKIT_PROJECT"
+    BUILD --platform=linux/amd64 +build-ticktock
     BUILD ./ast/parser+parser
     COPY (+earthly-linux-amd64/earthly --GO_GCFLAGS="${GO_GCFLAGS}") ./
     SAVE ARTIFACT ./earthly AS LOCAL ./build/linux/amd64/earthly
@@ -604,6 +594,7 @@ for-linux-arm64:
     ARG BUILDKIT_PROJECT
     ARG GO_GCFLAGS
     BUILD --platform=linux/arm64 ./buildkitd+buildkitd --BUILDKIT_PROJECT="$BUILDKIT_PROJECT"
+    BUILD --platform=linux/arm64 +build-ticktock
     BUILD ./ast/parser+parser
     COPY (+earthly-linux-arm64/earthly --GO_GCFLAGS="${GO_GCFLAGS}") ./
     SAVE ARTIFACT ./earthly AS LOCAL ./build/linux/arm64/earthly
@@ -615,6 +606,7 @@ for-darwin:
     ARG BUILDKIT_PROJECT
     ARG GO_GCFLAGS
     BUILD --platform=linux/amd64 ./buildkitd+buildkitd --BUILDKIT_PROJECT="$BUILDKIT_PROJECT"
+    BUILD --platform=linux/amd64 +build-ticktock
     BUILD ./ast/parser+parser
     COPY (+earthly-darwin-amd64/earthly --GO_GCFLAGS="${GO_GCFLAGS}") ./
     SAVE ARTIFACT ./earthly AS LOCAL ./build/darwin/amd64/earthly
@@ -625,6 +617,7 @@ for-darwin-m1:
     ARG BUILDKIT_PROJECT
     ARG GO_GCFLAGS
     BUILD --platform=linux/arm64 ./buildkitd+buildkitd --BUILDKIT_PROJECT="$BUILDKIT_PROJECT"
+    BUILD --platform=linux/arm64 +build-ticktock
     BUILD ./ast/parser+parser
     COPY (+earthly-darwin-arm64/earthly --GO_GCFLAGS="${GO_GCFLAGS}") ./
     SAVE ARTIFACT ./earthly AS LOCAL ./build/darwin/arm64/earthly
@@ -646,47 +639,16 @@ all-buildkitd:
         --platform=linux/arm64 \
         ./buildkitd+buildkitd --BUILDKIT_PROJECT="$BUILDKIT_PROJECT"
 
-dind-alpine:
-    DO --pass-args +BUILD_AND_FROM --TARGET=dind --OS_IMAGE=alpine --OS_VERSION=3.18 --DOCKER_VERSION=23.0.6-r7
-
-dind-ubuntu-20.04:
-    DO --pass-args +BUILD_AND_FROM --TARGET=dind --OS_IMAGE=ubuntu --OS_VERSION=20.04 --DOCKER_VERSION=5:24.0.5-1~ubuntu.20.04~focal
-
-dind-ubuntu-23.04:
-    DO --pass-args +BUILD_AND_FROM --TARGET=dind --OS_IMAGE=ubuntu --OS_VERSION=23.04 --DOCKER_VERSION=5:24.0.5-1~ubuntu.23.04~lunar
-
-# all-dind builds alpine and ubuntu dind containers for both linux amd64 and linux arm64
-all-dind:
-    RUN --no-cache date --utc +%Y%m%d%H%M%S > datetime
-    ARG DATETIME="$(cat datetime)"
-    BUILD \
-        --pass-args \
-        --platform=linux/amd64 \
-        --platform=linux/arm64 \
-        +dind-alpine --DATETIME=$DATETIME
-    BUILD \
-        --pass-args \
-        --platform=linux/amd64 \
-        --platform=linux/arm64 \
-        +dind-ubuntu-20.04 --DATETIME=$DATETIME
-    BUILD \
-        --pass-args \
-        --platform=linux/amd64 \
-        --platform=linux/arm64 \
-        +dind-ubuntu-23.04 --DATETIME=$DATETIME
-
 # all builds all of the following:
 # - Buildkitd for both linux amd64 and linux arm64
 # - Earthly for all supported environments linux amd64 and linux arm64, Darwin amd64 and arm64, and Windos amd64
 # - Earthly as a container image
 # - Prerelease version of earthly as a container image
-# - Dind alpine and ubuntu for both linux amd64 and linux arm64 as container images
 all:
     BUILD +all-buildkitd
     BUILD +earthly-all
     BUILD +earthly-docker
     BUILD +prerelease
-    BUILD +all-dind
 
 # lint-all runs all linting checks against the earthly project.
 lint-all:
@@ -704,19 +666,50 @@ lint-docs:
 # test-no-qemu runs tests without qemu virtualization by passing in dockerhub authentication and
 # using secure docker hub mirror configurations
 test-no-qemu:
-    BUILD --pass-args +test-quick
+    BUILD --pass-args +test-misc
     BUILD --pass-args +test-no-qemu-group1
     BUILD --pass-args +test-no-qemu-group2
     BUILD --pass-args +test-no-qemu-group3
     BUILD --pass-args +test-no-qemu-group4
+    BUILD --pass-args +test-no-qemu-group5
+    BUILD --pass-args +test-no-qemu-group6
+    BUILD --pass-args +test-no-qemu-group7
+    BUILD --pass-args +test-no-qemu-group8
+    BUILD --pass-args +test-no-qemu-group9
+    BUILD --pass-args +test-no-qemu-group10
+    BUILD --pass-args +test-no-qemu-group11
+    BUILD --pass-args +test-no-qemu-group12
     BUILD --pass-args +test-no-qemu-slow
 
-# test-quick runs the unit, offline, and go tests and ensures the earthly script does not write to stdout
-test-quick:
+# test-misc runs misc (non earthly-in-earthly) tests
+test-misc:
+    BUILD +test-misc-group1
+    BUILD +test-misc-group2
+    BUILD +test-misc-group3
+    BUILD +test-ast
+
+test-misc-group1:
     BUILD +unit-test
+
+test-misc-group2:
     BUILD +offline-test
+
+test-misc-group3:
     BUILD +earthly-script-no-stdout
-    BUILD --pass-args ./ast/tests+all
+
+test-ast:
+    BUILD +test-ast-group1
+    BUILD +test-ast-group2
+    BUILD +test-ast-group3
+
+test-ast-group1:
+    BUILD --pass-args ./ast/tests+group1
+
+test-ast-group2:
+    BUILD --pass-args ./ast/tests+group2
+
+test-ast-group3:
+    BUILD --pass-args ./ast/tests+group3
 
 # test-no-qemu-group1 runs the tests from ./tests+ga-no-qemu-group1
 test-no-qemu-group1:
@@ -736,6 +729,46 @@ test-no-qemu-group3:
 # test-no-qemu-group4 runs the tests from ./tests+ga-no-qemu-group4
 test-no-qemu-group4:
     BUILD --pass-args ./tests+ga-no-qemu-group4 \
+        --GLOBAL_WAIT_END="$GLOBAL_WAIT_END"
+
+# test-no-qemu-group5 runs the tests from ./tests+ga-no-qemu-group5
+test-no-qemu-group5:
+    BUILD --pass-args ./tests+ga-no-qemu-group5 \
+        --GLOBAL_WAIT_END="$GLOBAL_WAIT_END"
+
+# test-no-qemu-group6 runs the tests from ./tests+ga-no-qemu-group6
+test-no-qemu-group6:
+    BUILD --pass-args ./tests+ga-no-qemu-group6 \
+        --GLOBAL_WAIT_END="$GLOBAL_WAIT_END"
+
+# test-no-qemu-group7 runs the tests from ./tests+ga-no-qemu-group7
+test-no-qemu-group7:
+    BUILD --pass-args ./tests+ga-no-qemu-group7 \
+        --GLOBAL_WAIT_END="$GLOBAL_WAIT_END"
+
+# test-no-qemu-group8 runs the tests from ./tests+ga-no-qemu-group8
+test-no-qemu-group8:
+    BUILD --pass-args ./tests+ga-no-qemu-group8 \
+        --GLOBAL_WAIT_END="$GLOBAL_WAIT_END"
+
+# test-no-qemu-group9 runs the tests from ./tests+ga-no-qemu-group9
+test-no-qemu-group9:
+    BUILD --pass-args ./tests+ga-no-qemu-group9 \
+        --GLOBAL_WAIT_END="$GLOBAL_WAIT_END"
+
+# test-no-qemu-group10 runs the tests from ./tests+ga-no-qemu-group10
+test-no-qemu-group10:
+    BUILD --pass-args ./tests+ga-no-qemu-group10 \
+        --GLOBAL_WAIT_END="$GLOBAL_WAIT_END"
+
+# test-no-qemu-group11 runs the tests from ./tests+ga-no-qemu-group11
+test-no-qemu-group11:
+    BUILD --pass-args ./tests+ga-no-qemu-group11 \
+        --GLOBAL_WAIT_END="$GLOBAL_WAIT_END"
+
+# test-no-qemu-group12 runs the tests from ./tests+ga-no-qemu-group12
+test-no-qemu-group12:
+    BUILD --pass-args ./tests+ga-no-qemu-group12 \
         --GLOBAL_WAIT_END="$GLOBAL_WAIT_END"
 
 # test-no-qemu-slow runs the tests from ./tests+ga-no-qemu-slow
@@ -858,24 +891,46 @@ npm-update-all:
 
 # merge-main-to-docs merges the main branch into docs-0.8
 merge-main-to-docs:
-    FROM alpine/git
+    RUN git config --global user.name "littleredcorvette" && \
+        git config --global user.email "littleredcorvette@users.noreply.github.com" && \
+        git config --global url."git@github.com:".insteadOf "https://github.com/"
+
+    ARG TARGETARCH
+    # renovate: datasource=github-releases depName=cli/cli
+    ARG gh_version=v2.49.2
+    RUN curl -Lo ghlinux.tar.gz \
+      https://github.com/cli/cli/releases/download/$gh_version/gh_${gh_version#v}_linux_${TARGETARCH}.tar.gz \
+      && tar --strip-components=1 -xf ghlinux.tar.gz \
+      && rm ghlinux.tar.gz && mv ./bin/gh /usr/local/bin/gh
+
     ARG git_repo="earthly/earthly"
     ARG git_url="git@github.com:$git_repo"
+    ARG earthly_lib_version=3.0.1
+    ARG SECRET_PATH=littleredcorvette-id_rsa
+    DO --pass-args github.com/earthly/lib/utils/git:$earthly_lib_version+DEEP_CLONE \
+        --GIT_URL=$git_url --SECRET_PATH=$SECRET_PATH
+
     ARG to_branch="docs-0.8"
     ARG from_branch="main"
-    ARG earthly_lib_version=2.2.2
-    DO github.com/earthly/lib/ssh:$earthly_lib_version+ADD_KNOWN_HOSTS --target_file=~/.ssh/known_hosts
-    RUN git config --global user.name "littleredcorvette" && \
-        git config --global user.email "littleredcorvette@users.noreply.github.com"
-    GIT CLONE "$git_url" earthly
-    WORKDIR earthly
-    ARG git_hash=$(git rev-parse HEAD)
-    RUN --mount=type=secret,id=littleredcorvette-id_rsa,mode=0400,target=/root/.ssh/id_rsa \
-        git fetch --unshallow
-    RUN --push --mount=type=secret,id=littleredcorvette-id_rsa,mode=0400,target=/root/.ssh/id_rsa \
-        git checkout $to_branch && \
-        git merge $from_branch && \
-        git push
+
+    LET temp_pr_branch="soon-to-be-$to_branch"
+    RUN --push --secret GH_TOKEN=littleredcorvette-github-token --mount=type=secret,id=littleredcorvette-id_rsa,mode=0400,target=/root/.ssh/id_rsa \
+        # 1. checkout the docs branch and merge changes from main
+         git checkout $to_branch && git pull origin $to_branch &&\
+         git merge $from_branch && \
+        # 2. create a new temp branch to for a PR (can't push directly to protected branch)
+        git checkout -b $temp_pr_branch && git push -f origin $temp_pr_branch && \
+        # 3. create a new PR and wait till checks complete (if checks fail, close the PR)
+        gh pr create --title "Temp PR to merge $from_branch to $to_branch" --draft -B $to_branch \
+        --body "Opened by +merge-main-to-docs" --repo $git_repo && \
+        sleep 15 && \
+        ( \
+            timeout --signal=SIGINT 300 \
+            gh run watch $(gh run list --commit $(git rev-parse HEAD) -w "Check Docs for Broken Links" --json "databaseId" --jq '.[]|.databaseId') --exit-status || \
+            (gh pr close $temp_pr_branch --delete-branch && exit 1) \
+        ) && \
+        # 4. try to push the branch now that the PR checks have passed
+        git checkout $to_branch && (git push || (gh pr close $temp_pr_branch --delete-branch && exit 1))
 
 # check-broken-links checks for broken links in our docs website
 check-broken-links:
@@ -891,12 +946,55 @@ check-broken-links:
     ELSE
         RUN --no-cache $BLC_COMMAND &> $REPORT_FILE_NAME || true
     END
+    LET RESULT=$(grep -qE '^├─BROKEN─' $REPORT_FILE_NAME; echo $?)
+    LET NOCOLOR='\033[0m'
+    LET RED='\033[0;31m'
+    LET GREEN='\033[0;32m'
     IF [ $RESULT = "0" ]
         RUN --no-cache echo -e "${RED}Final Broken Links Report:${NOCOLOR}"
         RUN --no-cache grep --color=always -E '^(Getting links from|├─BROKEN─|Finished!|Elapsed)' $REPORT_FILE_NAME
         RUN exit 1
     ELSE
         RUN --no-cache echo -e "${GREEN}No Broken Links were found${NOCOLOR}"
+    END
+
+# open-pr-for-fork creates a new PR based on the given pr_number
+open-pr-for-fork:
+    RUN git config --global user.name "littleredcorvette" && \
+        git config --global user.email "littleredcorvette@users.noreply.github.com" && \
+        git config --global url."git@github.com:".insteadOf "https://github.com/"
+
+    ARG TARGETARCH
+    # renovate: datasource=github-releases depName=cli/cli
+    ARG gh_version=v2.49.2
+    RUN curl -Lo ghlinux.tar.gz \
+      https://github.com/cli/cli/releases/download/$gh_version/gh_${gh_version#v}_linux_${TARGETARCH}.tar.gz \
+      && tar --strip-components=1 -xf ghlinux.tar.gz \
+      && rm ghlinux.tar.gz && mv ./bin/gh /usr/local/bin/gh
+
+    ARG earthly_lib_version=3.0.1
+    ARG SECRET_PATH=littleredcorvette-id_rsa
+    ARG git_repo="earthly/earthly"
+    LET git_url="git@github.com:$git_repo"
+    DO --pass-args github.com/earthly/lib/utils/git:$earthly_lib_version+DEEP_CLONE \
+        --GIT_URL=$git_url --SECRET_PATH=$SECRET_PATH
+
+    ARG --required pr_number
+    RUN --no-cache --mount=type=secret,id=$SECRET_PATH,mode=0400,target=/root/.ssh/id_rsa \
+        --secret GH_TOKEN=littleredcorvette-github-token \
+        gh pr checkout $pr_number --branch "test-pr-$pr_number" --repo $git_repo && \
+        echo "checked out $(git rev-parse HEAD)" && \
+        git merge origin/main && \
+        git commit --allow-empty -m "please run the test" && \
+        git push -f origin HEAD
+    RUN --no-cache --secret GH_TOKEN=littleredcorvette-github-token echo $(gh pr list -H test-pr-$pr_number -B main --json number --jq '.[]|.number'|| "") > /tmp/result
+    LET test_pr=$(cat /tmp/result)
+    IF [[ -z $test_pr ]]
+        RUN --no-cache --secret GH_TOKEN=littleredcorvette-github-token \
+            gh pr create --title "Run tests for PR $pr_number" --draft \
+            --body "Running tests for https://github.com/$git_repo/pull/$pr_number" --repo $git_repo
+    ELSE
+        RUN --no-cache echo A matching test PR for PR $pr_number already exists: https://github.com/$git_repo/pull/$test_pr
     END
 
 check-broken-links-pr:
@@ -909,14 +1007,6 @@ check-broken-links-pr:
     IF [ -z $branch ]
         SET branch=$EARTHLY_GIT_BRANCH
     END
-    RUN --secret GH_TOKEN=littleredcorvette-github-token gh pr checks $branch --repo earthly/earthly | grep GitBook|awk '{print $4}' > url
+    RUN --secret GH_TOKEN=littleredcorvette-github-token gh pr checks $branch --repo earthly/earthly | grep GitBook|awk '{print $5}' > url
     ARG VERBOSE
     BUILD --pass-args +check-broken-links --ADDRESS=$(cat url)
-
-
-# BUILD_AND_FROM will issue a FROM and a BUILD commands for the provided target
-BUILD_AND_FROM:
-    FUNCTION
-    ARG --required TARGET
-    FROM --pass-args +$TARGET
-    BUILD --pass-args +$TARGET
